workspace:
  base: /go
  path: src/github.com/papillonyi/chitchart

pipeline:
  build:
    image: golang
    commands:
#    - go get
    - CGO_ENABLED=0 go build -tags netgo -a -v
#    - go test
  publish:
    image: plugins/docker
    repo: registry-vpc.cn-shanghai.aliyuncs.com/papillonyispace/chitchat
    username: andyi@live.cn
    password: 123456Y
    registry: registry-vpc.cn-shanghai.aliyuncs.com