workspace:
  base: /go
  path: src/github.com/papillonyi/chitchart

pipeline:
  build:
    image: golang
    commands:
#    - go get
    - go build
#    - go test
  publish:
    image: plugins/docker
    repo: registry-vpc.cn-shanghai.aliyuncs.com/papillonyispace/chitchat